version: "3.8"

services:
  # 1) PostgreSQL
  liu-db:
    image: postgres:13
    container_name: liu-db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     liu
      POSTGRES_PASSWORD: liu
      POSTGRES_DB:       liu
    ports:
      - "5400:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf

  # 2) Diagnostics UI (Streamlit)
  diagnostics-ui:
    build:
      context: .
      dockerfile: Dockerfile.diagnostics
    container_name: liu-streamlit-diag
    restart: unless-stopped
    depends_on:
      - liu-db
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./liu_samples:/app/liu_samples:rw
    command: >
      streamlit run flow_tester.py
      --server.port 8501
      --server.headless true
    environment:
      DSN: "${DSN}"
      TLOG_LEVEL: "${TLOG_LEVEL}"
      REFRESH_INTERVAL_MS: "${REFRESH_INTERVAL_MS}"
      MAX_ROWS: "${MAX_ROWS}"

  # 3) Live-Trades UI (Streamlit)
  live-trades-ui:
    build:
      context: .
      dockerfile: Dockerfile.live_trades
    container_name: liu-streamlit-live
    restart: unless-stopped
    depends_on:
      - liu-db
      - live-trader
    ports:
      - "8502:8502"
    environment:
      DSN:                  "postgresql://liu:liu@liu-db:5432/liu"
      TRADEPLAN_DIR:        "/app/liu_samples"
      TLOG_LEVEL:           "DEBUG"
      REFRESH_INTERVAL_MS:  "5000"
      MAX_ROWS:             "50"
    volumes:
      - ./liu_samples:/app/liu_samples:ro

  # 4) Backtest runner
  backtest:
    build:
      context: .
      dockerfile: Dockerfile.fixit
    container_name: liu-backtest
    depends_on:
      - liu-db
    volumes:
      - ./liu_samples:/app/liu_samples:rw
    environment:
      DSN: "postgresql://liu:liu@liu-db:5432/liu"

  # 5) Fix-it bot
  fix-it-bot:
    build:
      context: .
      dockerfile: Dockerfile.fixit
    container_name: liu-fix-it
    restart: "no"
    depends_on:
      - liu-db
    volumes:
      - ./liu_samples:/app/liu_samples:rw
    environment:
      DSN:        "postgresql://liu:liu@liu-db:5432/liu"
      TLOG_LEVEL: "DEBUG"
    command: []

  # 6) Live trader (paper-mode)
  live-trader:
    build:
      context: .
      dockerfile: Dockerfile.live
    container_name: liu-live
    restart: on-failure
    env_file:
      - .env
    entrypoint: ["liu"]
    command:
      - run
      - live
      - "--tradeplan"
      - "/app/liu_samples/tradeplan.toml"
      - "--log-level"
      - "INFO"
    environment:
      APCA_API_KEY_ID:     ${APCA_API_KEY_ID}
      APCA_API_SECRET_KEY: ${APCA_API_SECRET_KEY}
      APCA_API_BASE_URL:   https://paper-api.alpaca.markets/v2
      ALPACA_STREAM_URL:   wss://stream.data.alpaca.markets/v2/sip
      ALPACA_DATA_FEED:    iex
      DATA_CONNECTOR:      alpaca
      LIU_BROKER:          alpaca
      DSN:                 "postgresql://liu:liu@liu-db:5432/liu"
      TRADEPLAN_DIR:       "/app/liu_samples"
      TLOG_LEVEL:          "DEBUG"
    volumes:
      - ./liu_samples:/app/liu_samples:ro

  # 7) Prometheus
  liu-prometheus:
    image: prom/prometheus:latest
    container_name: liu-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  # 8) Grafana
  liu-grafana:
    image: grafana/grafana:latest
    container_name: liu-grafana
    restart: unless-stopped
    depends_on:
      - liu-prometheus
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED:  "true"
      GF_SECURITY_ADMIN_PASSWORD: "liu"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

  # 9) AI Assistant (FastAPI)
  assistant:
    build:
      context: ./assistant
      dockerfile: Dockerfile.assistant
    container_name: liu-assistant
    restart: unless-stopped
    depends_on:
      - liu-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt/build:rw

volumes:
  db_data:
    driver: local
