# build/Dockerfile.fixit
FROM python:3.10-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
 && rm -rf /var/lib/apt/lists/* \
 && pip install --no-cache-dir \
      liualgotrader \
      psycopg2-binary

WORKDIR /app

COPY engine-wrapper/fix_it_bot.py .

ENTRYPOINT ["python3","fix_it_bot.py"]
